# Generated by Django 5.1.3 on 2024-11-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
