# Generated by Django 5.1.3 on 2024-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("FROZEN", "Frozen"),
                    ("CLOSED", "Closed"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
